stages:
  - test
  - build
  
test:
  stage: test
  script: echo 'running tests....'
  tags:
    - deploy
  
build:
  stage: build
  script: 
    - vue build src/main.js
    - docker build -t paredros-gateway .
  tags:
    - deploy
