stages:
  - test
  - build
  
test:
  stage: test
  script: echo 'running tests....'
  tags:
    - deploy
  
build:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
    - docker build -t paredros-gateway .
  tags:
    - deploy
