stages:
  - test
  - vue-build
  - docker-build
  
test:
  stage: test
  script: echo 'running tests....'
  tags:
    - deploy
  
vue-build:
  stage: vue-build
  script: vue build src/main.js
  tags:
    - deploy

docker-build:
  stage: docker-build
  script: docker build -t paredros-gateway .
  tags:
    - deploy
