stages:
  - test
  - build
  
test-image:
  stage: test
  script: echo 'running tests....'
  tags:
    - deploy

install-dependencies:
  stage: build
  script: npm install
  tags:
    - deploy
  
vue-build:
  stage: build
  script: npm run build
  tags:
    - deploy

docker-build:
  stage: build
  script: docker build -t paredros-gateway .
  tags:
    - deploy
