stages:
  - test
  - build
  
test-image:
  stage: test
  script: echo 'running tests....'
  tags:
    - deploy
  
build-image:
  stage: build
  script: docker build -t paredros-gateway .
  tags:
    - deploy
